version: '3.8'

services:
  
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment: 
      - APP_NAME=app
    expose: 
      - 8080

  nginx:
    build: ./configs/nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80